# Generated by Django 3.1.5 on 2021-01-06 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unique_address',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
